[project]
name = "classicos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "mkdocs>=1.6.1",
    "mkdocs-jupyter>=0.24.1",
    "mkdocs-material>=9.7.1",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "pingouin>=0.5.5",
    "plotly>=6.5.2",
    "plotnine>=0.15.2",
    "pyjanitor>=0.32.9",
    "pymdown-extensions>=10.20.1",
    "pyomo>=6.9.5",
    "quarto>=0.1.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.0",
    "setuptools>=80.10.1",
    "statsmodels>=0.14.6",
]
