project:
  type: website
  output-dir: ../book

execute: 
  freeze: true

website:
  announcement: 
      content: "**Atenção** - Se você achou este conteúdo útil, considere apoiar o projeto me seguindo no Youtube, Instagram ou LinkedIn! 🚀" 
      position: below-navbar 
  title: "Clássicos da Ciência de Dados"
  description: "Uma jornada prática através dos principais casos de uso em ciência de dados"
  site-url: https://classicos-ds.netlify.app/
  bread-crumbs: true
  page-navigation: true
  navbar:
    background: "#f5e003"
    pinned: true   
    title: "Clássicos da Ciência de Dados"
    logo-link: https://www.resolvedortech.com.br/
    collapse: true
    search: true
    right: 
      - icon: github
        href: https://github.com/thiagoysyuki
        aria-label: "GitHub"
      - icon: linkedin
        href: https://linkedin.com/in/thiagoyuki
        aria-label: "LinkedIn"
      - icon: youtube
        href: https://www.youtube.com/@resolvedortech
        aria-label: "YouTube"
      - icon: instagram
        href: https://www.instagram.com/resolvedortech/
        aria-label: "Instagram"
  sidebar: 
    title: "Clássicos da Ciência de Dados"
    logo: "static/logo.png"
    logo-alt: "Logo da Clássicos da Ciência de Dados"
    logo-width: 80
    logo-height: 80
    logo-position: left
    logo-link: https://www.resolvedortech.com.br/
    style: docked
    search: true 
    contents:
      - text: Bem Vindo(a)
        href: index.qmd
      - section: Descritivo/descritivo.qmd
        contents:
        - section: "Gráficos e Estatísticas"
          contents:          
          - Descritivo/Gráficos/gdp.ipynb
      
      - section: Preditivo/predicao.qmd 
        contents:
          - section: "Classificação"
            contents:
            - Preditivo/Classificação/iris.ipynb
            - Preditivo/Classificação/titanic.ipynb 
            - Preditivo/Classificação/pinguins.ipynb
            - Preditivo/Classificação/cancer.ipynb
            - Preditivo/Classificação/wine_quality.ipynb
          - section: "Regressão"
            contents:
            - Preditivo/Regressão/housing.ipynb
            - Preditivo/Regressão/gasoline.qmd
            - Preditivo/Regressão/airpassengers.ipynb
      - section: Prescritivo/prescritivo.qmd
        contents:
          - section: "Programação Linear"
            contents:
            - Prescritivo/PL/dieta.ipynb
            - Prescritivo/PL/caixeiro.ipynb

  page-footer:
    left: "Direitos Autorais de Thiago Yuki, 2025"
    center: "Clássicos da Ciência de Dados" 
    right: 
      - icon: github
        href: https://github.com/thiagoysyuki
        aria-label: "GitHub"
      - icon: youtube
        href: https://www.youtube.com/@resolvedortech
        aria-label: "YouTube"
      - icon: instagram
        href: https://www.instagram.com/resolvedortech/
        aria-label: "Instagram"
      - icon: linkedin
        href: https://linkedin.com/in/thiagoyuki
        aria-label: "LinkedIn"



bibliography: static/references.bib
csl: static/abnt.csl

format:
  html:
    code-fold: true
    code-summary: "Mostrar/Ocultar Código"    
    theme:
      - spacelab
    highlight-style: dracula
    toc: true
    toc-location: right
    toc-depth: 5
    
jupyter: python3
lang: pt-BR